bbs/urls.py
from django.urls import path
import bbs.views

app_name = 'bbs'

urlpatterns = [
    path('selectAll', bbs.views.SelectAll.as_view(), name='selectAll'),
    path('deltail/<int:pk>', bbs.views.Detail.as_view(), name='detail'),
    path('update/<int:pk>', bbs.views.Update.as_view(), name='update'),
    path('delete', bbs.views.delete, name='delete'),
    path('create', bbs.views.Create.as_view(), name='create'),
]

chart_page/urls.py
from django.conf.urls import url
from django.urls import path, include

from chart_page import views

app_name = 'chart'

urlpatterns = [
    url(r'^traffic/?$', views.traffic, name='traffic'),
    url(r'^education/?$', views.education, name='education'),
    url(r'^environment/?$', views.environment, name='environment'),
    url(r'^medical_crime/?$', views.medical_crime, name='medical_crime'),
    url(r'^result/?$', views.result, name='result'),
    url(r'^rank/?$', views.rank, name='rank'),
    path('traffic-chart/', views.traffic_chart, name='traffic-chart'),
    path('parking-chart/', views.parking_chart, name='parking-chart'),
    path('commute-chart/', views.commute_chart, name='commute-chart'),
    path('school_num-chart/', views.school_num_chart, name='school_num-chart'),
    path('student_num-chart/', views.student_num_chart, name='student_num-chart'),
    path('teacher_num-chart/', views.teacher_num_chart, name='teacher_num-chart'),
    path('park-chart/', views.park_chart, name='park-chart'),
    path('garbage-chart/', views.garbage_chart, name='garbage-chart'),
    path('dust-chart/', views.dust_chart, name='dust-chart'),
    path('green-chart/', views.green_chart, name='green-chart'),
    path('hospital_sickbed-chart/', views.hospital_sickbed_chart, name='hospital_sickbed-chart'),
    path('crime-chart/', views.crime_chart, name='crime-chart'),
    path('pharmacy-chart/', views.pharmacy_chart, name='pharmacy-chart'),
    path('seoul_traffic-chart/', views.seoul_traffic_chart, name='seoul_traffic-chart'),
    path('seoul_medical-chart/', views.seoul_medical_chart, name='seoul_medical-chart'),
    path('seoul_envi-chart/', views.seoul_envi_chart, name='seoul_envi-chart'),
    path('seoul_education-chart/', views.seoul_edu_chart, name='seoul_education-chart'),
]

seoul/urls.py
from django.contrib import admin
from django.urls import path, include

from seoul import views
#sol
import member.urls
import map_data.urls
import member.views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('chart_page/', include('chart_page.urls')),
    path('', views.main),
    #sol
    path('member/',include(member.urls)),
    path('map_data/',include(map_data.urls)),
    path('',member.views.Main,name='main'),
    #ha
    path('bbs/', include('bbs.urls')),
    path('map/', include('map.urls')),
    # path('cul/', include('culture.urls')),
]

chart_page/models.py
from django.db import models

# Create your models here.
class Goo(models.Model):
    gu = models.CharField(max_length=100)

class Traffic(models.Model):
        register_car = models.PositiveIntegerField()
        parking_lot = models.PositiveIntegerField()
        bike = models.PositiveIntegerField()
        bus = models.PositiveIntegerField()
        trail = models.PositiveIntegerField()
        bus_trail = models.PositiveIntegerField()
        mycar = models.PositiveIntegerField()
        gu = models.ForeignKey(Goo, on_delete=models.CASCADE)

class Education(models.Model):
    garden = models.FloatField()
    element = models.FloatField()
    middle = models.FloatField()
    high = models.FloatField()
    garden_num= models.FloatField()
    element_num = models.FloatField()
    middle_num = models.FloatField()
    high_num = models.FloatField()
    garden_gyo = models.FloatField()
    element_gyo = models.FloatField()
    middle_gyo = models.FloatField()
    high_gyo = models.FloatField()
    gu = models.ForeignKey(Goo, on_delete=models.CASCADE)

class SeoulData(models.Model):
    safety = models.FloatField()
    medical = models.FloatField()
    medical_room = models.FloatField()
    environment = models.FloatField()
    traffic = models.FloatField()
    education = models.FloatField()
    gu = models.ForeignKey(Goo, on_delete=models.CASCADE)

class EnvironmentData(models.Model):
    park = models.FloatField()
    garbage = models.FloatField()
    dust = models.FloatField()
    green = models.FloatField()
    gu = models.ForeignKey(Goo, on_delete=models.CASCADE)

class Medical_CrimeData2(models.Model):
    hospital = models.FloatField()
    pharmacy = models.FloatField()
    sickbed = models.FloatField()
    crime_occ = models.FloatField()
    crime_arr = models.FloatField()
    gu = models.ForeignKey(Goo, on_delete=models.CASCADE)

chart_page/views.py
from django.db.models import Sum
from django.shortcuts import render
from django.http.response import HttpResponseRedirect, HttpResponse, JsonResponse

from chart_page.models import *


def traffic(request):
    return render(request, 'chart_page/traffic.html')

def education(request):
    return render(request, 'chart_page/education.html')

def result(request):
    return render(request, 'chart_page/result.html')

def rank(request):
    return render(request, 'chart_page/rank.html')

def environment(request):
    return render(request, 'chart_page/environment.html')

def medical_crime(request):
    return render(request, 'chart_page/medical_crime.html')

def traffic_chart(request):
    labels = []
    data = []

    queryset = Traffic.objects.values('gu__gu').annotate(car=Sum('register_car')).order_by('-car')

    for entry in queryset:
        labels.append(entry['gu__gu'])
        data.append(entry['car'])
    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })

def parking_chart(request):
    labels = []
    data = []

    queryset = Traffic.objects.values('gu__gu').annotate(parking=Sum('parking_lot')).order_by('-parking')

    for entry in queryset:
        labels.append(entry['gu__gu'])
        data.append(entry['parking'])
    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })

def commute_chart(request):
    labels = []
    bus = []
    trail = []
    bus_trail = []
    mycar = []

    queryset = Traffic.objects.values('gu__gu','bus','trail','bus_trail','mycar')
    for entry in queryset:
        labels.append(entry['gu__gu'])
        bus.append(entry['bus'])
        trail.append(entry['trail'])
        bus_trail.append(entry['bus_trail'])
        mycar.append(entry['mycar'])

    return JsonResponse(data={
        'labels': labels,
        'bus': bus,
        'trail': trail,
        'bus_trail': bus_trail,
        'mycar': mycar,
    })

def school_num_chart(request):
    labels = []
    garden = []
    element = []
    middle = []
    high = []

    queryset = Education.objects.values('gu__gu', 'garden', 'element', 'middle', 'high')
    for entry in queryset:
        labels.append(entry['gu__gu'])
        garden.append(entry['garden'])
        element.append(entry['element'])
        middle.append(entry['middle'])
        high.append(entry['high'])

    return JsonResponse(data={
        'labels': labels,
        'garden': garden,
        'element': element,
        'middle': middle,
        'high': high,
    })

def student_num_chart(request):
    labels = []
    garden_num = []
    element_num = []
    middle_num = []
    high_num = []

    queryset = Education.objects.values('gu__gu', 'garden_num', 'element_num', 'middle_num', 'high_num')
    for entry in queryset:
        labels.append(entry['gu__gu'])
        garden_num.append(entry['garden_num'])
        element_num.append(entry['element_num'])
        middle_num.append(entry['middle_num'])
        high_num.append(entry['high_num'])

    return JsonResponse(data={
        'labels': labels,
        'garden_num': garden_num,
        'element_num': element_num,
        'middle_num': middle_num,
        'high_num': high_num,
    })

def teacher_num_chart(request):
    labels = []
    garden_gyo = []
    element_gyo = []
    middle_gyo = []
    high_gyo = []

    queryset = Education.objects.values('gu__gu', 'garden_gyo', 'element_gyo', 'middle_gyo', 'high_gyo')
    for entry in queryset:
        labels.append(entry['gu__gu'])
        garden_gyo.append(entry['garden_gyo'])
        element_gyo.append(entry['element_gyo'])
        middle_gyo.append(entry['middle_gyo'])
        high_gyo.append(entry['high_gyo'])

    return JsonResponse(data={
        'labels': labels,
        'garden_gyo': garden_gyo,
        'element_gyo': element_gyo,
        'middle_gyo': middle_gyo,
        'high_gyo': high_gyo,
    })

def seoul_traffic_chart(request):
    labels = []
    data = []

    queryset = SeoulData.objects.values('gu__gu').annotate(traffic=Sum('traffic')).order_by('-traffic')

    for entry in queryset:
        labels.append(entry['gu__gu'])
        data.append(entry['traffic'])
    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })

def seoul_medical_chart(request):
    labels = []
    medical = []
    medical_room = []

    queryset = SeoulData.objects.values('gu__gu','medical','medical_room').order_by('-medical_room')

    for entry in queryset:
        labels.append(entry['gu__gu'])
        medical.append(entry['medical'])
        medical_room.append(entry['medical_room'])
    return JsonResponse(data={
        'labels': labels,
        'medical': medical,
        'medical_room' : medical_room
    })

def seoul_envi_chart(request):
    labels = []
    data = []

    queryset = SeoulData.objects.values('gu__gu','environment').order_by('-environment')

    for entry in queryset:
        labels.append(entry['gu__gu'])
        data.append(entry['environment'])
    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })

def seoul_edu_chart(request):
    labels = []
    data = []

    queryset = SeoulData.objects.values('gu__gu', 'education').order_by('-education')

    for entry in queryset:
        labels.append(entry['gu__gu'])
        data.append(entry['education'])
    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })

def park_chart(request):
    labels = []
    data = []

    queryset = EnvironmentData.objects.values('gu__gu', 'park').order_by('-park')

    for entry in queryset:
        labels.append(entry['gu__gu'])
        data.append(entry['park'])
    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })

def garbage_chart(request):
    labels = []
    data = []

    queryset = EnvironmentData.objects.values('gu__gu', 'garbage').order_by('-garbage')

    for entry in queryset:
        labels.append(entry['gu__gu'])
        data.append(entry['garbage'])
    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })

def dust_chart(request):
    labels = []
    data = []

    queryset = EnvironmentData.objects.values('gu__gu', 'dust').order_by('-dust')

    for entry in queryset:
        labels.append(entry['gu__gu'])
        data.append(entry['dust'])
    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })

def green_chart(request):
    labels = []
    data = []

    queryset = EnvironmentData.objects.values('gu__gu', 'green').order_by('-green')

    for entry in queryset:
        labels.append(entry['gu__gu'])
        data.append(entry['green'])
    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })

def hospital_sickbed_chart(request):
    labels = []
    hospital = []
    sickbed = []

    queryset = Medical_CrimeData2.objects.values('gu__gu', 'hospital', 'sickbed').order_by('-sickbed')

    for entry in queryset:
        labels.append(entry['gu__gu'])
        hospital.append(entry['hospital'])
        sickbed.append(entry['sickbed'])
    return JsonResponse(data={
        'labels': labels,
        'hospital': hospital,
        'sickbed': sickbed,
    })

def crime_chart(request):
    labels = []
    crime_occ = []
    crime_arr = []

    queryset = Medical_CrimeData2.objects.values('gu__gu', 'crime_occ', 'crime_arr').order_by('-crime_occ')

    for entry in queryset:
        labels.append(entry['gu__gu'])
        crime_occ.append(entry['crime_occ'])
        crime_arr.append(entry['crime_arr'])
    return JsonResponse(data={
        'labels': labels,
        'crime_occ': crime_occ,
        'crime_arr': crime_arr,
    })

def pharmacy_chart(request):
    labels = []
    data = []

    queryset = Medical_CrimeData2.objects.values('gu__gu', 'pharmacy').order_by('-pharmacy')

    for entry in queryset:
        labels.append(entry['gu__gu'])
        data.append(entry['pharmacy'])
    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })

chart_page/templates/chart_page/education.html
{% extends "base.html" %}

{% block contenttitle %}교육 차트{% endblock %}
{% block title %}교육 차트{% endblock %}

{% block head %}
<style>
canvas[data-class]{
    width:600px;
    height:427px;
}
.hanglue{
    font-family:'Malgun Gothic';
    font-size:15pt;
    font-weight:bold;
}
.item_none{
    height:80px;
    margin-left:20px;
    height:40px;
}



label[for=eyes_01], label[for=eyes_02], label[for=nose_01], label[for=nose_02], label[for=mouth_01], label[for=mouth_02] {
    margin-left:20px;
    height:inherit;
}
.eyes_01{
    width:100px;
    height:40px;
}
.eyes_02{
    width:50px;
    height:40px;
}
.nose_01{
    width:30px;
    height:50px;
}
.nose_02{
    width:30px;
    height:30px;
}
.mouth_01{
    width:50px;
    height:30px;
}
.mouth_02{
    width:60px;
    height:30px;
}

</style>

{% endblock %}

{% block content %}
    <div class="row clearfix">
                <!-- Line Chart -->
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <div class="hanglue">학교수</div>
                        </div>
                        <div class="body">
                             <canvas id="school_num-chart" data-url="{% url 'chart:school_num-chart' %}" height="150"></canvas>
                        </div>
                    </div>
                </div>
                <!-- #END# Line Chart -->
                <!-- Bar Chart -->
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <div class="hanglue">학급당 학생수</div>
                        </div>
                        <div class="body">
                             <canvas id="student_num-chart" data-url="{% url 'chart:student_num-chart' %}" height="150"></canvas>
                        </div>
                    </div>
                </div>
                <!-- #END# Bar Chart -->
            </div>

            <div class="row clearfix">
                <!-- Radar Chart -->
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <div class="hanglue">학급당 교사수</div>
                        </div>
                        <div class="body">
                             <canvas id="teacher_num-chart" data-url="{% url 'chart:teacher_num-chart' %}" height="150"></canvas>
                        </div>
                    </div>
                </div>
                <!-- #END# Radar Chart -->
                <!-- Pie Chart -->
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <div class="hanglue">미정</div>
                        </div>
                        <div class="body">
                            <canvas id="pie_chart" height="150"></canvas>
                        </div>
                    </div>
                </div>
                <!-- #END# Pie Chart -->
            </div>



{% csrf_token %}
{% endblock %}
 
{% block script %}

  <div id="container" style="width: 75%;">
{#    <canvas id="population-chart" data-url="{% url 'chart:population-chart' %}"></canvas>#}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>
  {# schoolNum #}
    $(function schoolNumChart() {

      var $schoolNumChart = $("#school_num-chart");
      $.ajax({
        url: $schoolNumChart.data("url"),
        success: function (data) {
            console.log(data)
          var ctx = $schoolNumChart[0].getContext("2d");
          new Chart(ctx, {
            type: 'bar',
                  data: {
                      labels: data.labels,
                      datasets: [
                              {
                                  label: '유치원',
                        data: data.garden,
                        backgroundColor: '#E1DCD9',
                      },
                      {
                          label: '초등학교',
                        data: data.element,
                        backgroundColor: '#8F8681',
                      },
                      {
                          label: '중학교',
                        data: data.middle,
                        backgroundColor: '#A67F78',
                      },
                          {
                              label: '고등학교',
                        data: data.high,
                        backgroundColor: '#32435F',
                      }
                      ]
                  },
            options: {
                scales: {
            xAxes: [{
                stacked: true
            }],
            yAxes: [{
                stacked: true
            }]
        },
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: ' the number of schools Chart'
              }
            }
          });

        }
      });

    });

     {# studentNum #}
    $(function studentNumChart() {

      var $studentNumChart = $("#student_num-chart");
      $.ajax({
        url: $studentNumChart.data("url"),
        success: function (data) {
            console.log(data)
          var ctx = $studentNumChart[0].getContext("2d");
          new Chart(ctx, {
            type: 'bar',
                  data: {
                      labels: data.labels,
                      datasets: [
                              {
                                  label: '유치원',
                        data: data.garden_num,
                        backgroundColor: '#D1DDDB',
                      },
                      {
                          label: '초등학교',
                        data: data.element_num,
                        backgroundColor: '#85B8CB',
                      },
                      {
                          label: '중학교',
                        data: data.middle_num,
                        backgroundColor: '#1D6A96',
                      },
                          {
                              label: '고등학교',
                        data: data.high_num,
                        backgroundColor: '#283B42',
                      }
                      ]
                  },
            options: {
                scales: {
            xAxes: [{
                stacked: true
            }],
            yAxes: [{
                stacked: true
            }]
        },
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: ' the number of student num'
              }
            }
          });

        }
      });

    });

     {# teacherNum #}
    $(function teacherNumChart() {

      var $teacherNumChart = $("#teacher_num-chart");
      $.ajax({
        url: $teacherNumChart.data("url"),
        success: function (data) {
            console.log(data)
          var ctx = $teacherNumChart[0].getContext("2d");
          new Chart(ctx, {
            type: 'bar',
                  data: {
                      labels: data.labels,
                      datasets: [
                              {
                                  label: '유치원',
                        data: data.garden_gyo,
                        backgroundColor: '#FFC2C3',
                      },
                      {
                          label: '초등학교',
                        data: data.element_gyo,
                        backgroundColor: '#FE7773',
                      },
                      {
                          label: '중학교',
                        data: data.middle_gyo,
                        backgroundColor: '#E81E25',
                      },
                          {
                              label: '고등학교',
                        data: data.high_gyo,
                        backgroundColor: '#0E0301',
                      }
                      ]
                  },
            options: {
                scales: {
            xAxes: [{
                stacked: true
            }],
            yAxes: [{
                stacked: true
            }]
        },
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: ' the number of teacher num'
              }
            }
          });

        }
      });

    });



  </script>

{% endblock %}

chart_page/templates/chart_page/environment.html
{% extends "base.html" %}

{% block contenttitle %}환경 차트{% endblock %}
{% block title %}환경 차트{% endblock %}

{% block head %}
<style>
canvas[data-class]{
    width:600px;
    height:427px;
}
.hanglue{
    font-family:'Malgun Gothic';
    font-size:15pt;
    font-weight:bold;
}
.item_none{
    height:80px;
    margin-left:20px;
    height:40px;
}



label[for=eyes_01], label[for=eyes_02], label[for=nose_01], label[for=nose_02], label[for=mouth_01], label[for=mouth_02] {
    margin-left:20px;
    height:inherit;
}
.eyes_01{
    width:100px;
    height:40px;
}
.eyes_02{
    width:50px;
    height:40px;
}
.nose_01{
    width:30px;
    height:50px;
}
.nose_02{
    width:30px;
    height:30px;
}
.mouth_01{
    width:50px;
    height:30px;
}
.mouth_02{
    width:60px;
    height:30px;
}

</style>

{% endblock %}

{% block content %}
    <div class="row clearfix">
                <!-- Line Chart -->
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <div class="hanglue">공원수</div>
                        </div>
                        <div class="body">
                             <canvas id="park-chart" data-url="{% url 'chart:park-chart' %}" height="150"></canvas>
                        </div>
                    </div>
                </div>
                <!-- #END# Line Chart -->
                <!-- Bar Chart -->
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <div class="hanglue">쓰레기배출량</div>
                        </div>
                        <div class="body">
                             <canvas id="garbage-chart" data-url="{% url 'chart:garbage-chart' %}" height="150"></canvas>
                        </div>
                    </div>
                </div>
                <!-- #END# Bar Chart -->
            </div>

            <div class="row clearfix">
                <!-- Radar Chart -->
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <div class="hanglue">먼지</div>
                        </div>
                        <div class="body">
                            <canvas id="dust-chart" data-url="{% url 'chart:dust-chart' %}" height="150"></canvas>
                        </div>
                    </div>
                </div>
                <!-- #END# Radar Chart -->
                <!-- Pie Chart -->
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <div class="hanglue">녹지화 면적</div>
                        </div>
                        <div class="body">
                            <canvas id="green-chart" data-url="{% url 'chart:green-chart' %}" height="150"></canvas>
                        </div>
                    </div>
                </div>
                <!-- #END# Pie Chart -->
            </div>



{% csrf_token %}
{% endblock %}
 
{% block script %}

  <div id="container" style="width: 75%;">
{#    <canvas id="population-chart" data-url="{% url 'chart:population-chart' %}"></canvas>#}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>
    $(function parkChart() {

      var $parkChart = $("#park-chart");
      $.ajax({
        url: $parkChart.data("url"),
        success: function (data) {
          var ctx = $parkChart[0].getContext("2d");
          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.labels,
              datasets: [{
                label: '공원수',
                backgroundColor: "#91D4C2",
                data: data.data
              }]
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Park Chart'
              }
            }
          });

        }
      });

    });

     $(function garbageChart() {

      var $garbageChart = $("#garbage-chart");
      $.ajax({
        url: $garbageChart.data("url"),
        success: function (data) {
          var ctx = $garbageChart[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.labels,
              datasets: [{
                label: '쓰레기 배출량',
                  backgroundColor: '#E5BB4B',
                data: data.data
              }]
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Garbage Chart'
              }
            }
          });

        }
      });

    });

    $(function dustChart() {
      var i = 0;
      var $dustChart = $("#dust-chart");
      {#alert('1')#}
      $.ajax({
        url: $dustChart.data("url"),
        success: function (data) {
          var ctx = $dustChart[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
                  data: {
                      labels: data.labels,
                      datasets: [
                              {
                                  label: '미세먼지',
                        data: data.data,
                        backgroundColor: '#CC8A56',
                      },
                      ]
                  },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: ' Dust Chart'
              }
            }
          });

        }
      });

    });

    $(function greenChart() {

      var $greenChart = $("#green-chart");
      $.ajax({
        url: $greenChart.data("url"),
        success: function (data) {
          var ctx = $greenChart[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.labels,
              datasets: [{
                label: '녹지화 면적',
                  backgroundColor: '#45BB89',
                data: data.data
              }]
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Green Chart'
              }
            }
          });

        }
      });

    });


  </script>

{% endblock %}